"""add indexes to transacoes

Revision ID: b9ba38a434e1
Revises: aff663516ec3
Create Date: 2026-07-07 21:15:01.461032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ba38a434e1'
down_revision: Union[str, None] = 'aff663516ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_transacoes_categoria', 'transacoes', ['categoria_id'], unique=False)
    op.create_index('idx_transacoes_usuario_data', 'transacoes', ['usuario_id', 'data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transacoes_usuario_data', table_name='transacoes')
    op.drop_index('idx_transacoes_categoria', table_name='transacoes')
    # ### end Alembic commands ###
